ALTER PROCEDURE [dbo].[spGetTinhLuongThang_TG]
	@UName NVARCHAR(100) ='admin',
	@NNgu INT =0,
	@DVi INT = -1,
	@XN INT = -1,
	@TO INT = -1,
	@NgayCC INT = 26,
	@NgayCLV INT = 26,
	@TNGAY Date ='2023-03-01',
	@DNGAY Date ='2023-03-31',
	@NgayBu FLOAT = 0, -- ngày bù lễ tết, bù ...
	@ThuongDoanhThu BIT = 1,
	@LOAI INT = 1
AS 
BEGIN

	DECLARE @NgayBD Date
	DECLARE @NgayKT Date
	SET @NgayBD = @TNGAY
	SET @NgayKT = @DNGAY

	--lay danh sach cong nhan tinh luong trong gai doan
	SELECT * INTO #CN FROM dbo.MGetListNhanSuFormToDate(@UName,@NNgu, @DVi, @XN, @TO, @TNGAY, @DNGAY)
	
	--Tao table tam luu tinh luong thang
--	[THANG] [datetime],[ID_CN] [bigint],[ID_TO] [bigint],[ID_CTL] [bigint],[ID_DV] [BIGINT],MS_CTL NVARCHAR(10),[ID_LCV] [BIGINT],NGAY_CONG_CHUAN INT,NGAY_CONG_LV INT,
--	[ID_XN] [int],[ID_TT_HT] [int],[NGAY_VAO_CTY] [datetime],[NGAY_NGHI_VIEC] [datetime],
--[DL] FLOAT,[CN] FLOAT,[VM] FLOAT,[TD] FLOAT,[LUONG_HDLD] FLOAT,[LUONG_NGAY_CONG] FLOAT,[GLT] FLOAT,TIEN_THEM_GIO FLOAT,[LUONG_PHEP_NGAY] FLOAT,[NGAY_LE] FLOAT)
CREATE TABLE #TBLuongThang([THANG] [datetime],[ID_CN] [bigint],[ID_TO] [bigint],[ID_CTL] [bigint],[ID_DV] [BIGINT],MS_CTL NVARCHAR(10),[ID_LCV] [BIGINT],NGAY_CONG_CHUAN INT,NGAY_CONG_LV INT,
[ID_XN] [int],[ID_TT_HT] [int],[NGAY_VAO_CTY] [datetime],[NGAY_NGHI_VIEC] [DATETIME],
[DL] [float] ,[CN] [float] ,[VM] [float] ,[TD] [float] ,[LUONG_HDLD] [FLOAT],[LUONG_NGAY_CONG] FLOAT,[LUONG_NGAY_CN] [float] ,[GLT] [float] ,[TIEN_THEM_GIO] [float] ,[THUONG_HIEU_SUAT] [float] ,[THUONG_C_HANH] [float] ,
[LUONG_PHEP_NGAY] [float] ,[LUONG_PHEP_TIEN] [float] ,[NGAY_LE] [float] ,[LUONG_LE_TET] [float] ,[THUONG_HTNV] [float] ,[TRO_CAP_CN] [float] ,[TIEN_XANG] [float] ,[THUONG] [float] ,[BU_NCCB] [float] ,
[LUONG_CA_THANG] [float] ,[KHAU_TRU_TAM_UNG] [float] ,[BHXH_BHTN] [float] ,[BHYT] [float] ,[KHAU_TRU] [float] ,[THUE_TNCN] [float] ,[THUC_LANH] [float] ,[KY_NHAN] [FLOAT])

	SELECT * INTO #CCTHANG FROM CHAM_CONG_THANG WHERE THANG = @TNGAY



	--Lay danh sach cong nhan tinh luong
	INSERT INTO #TBLuongThang (THANG, ID_DV, ID_XN, ID_TO, ID_CN, ID_TT_HT, NGAY_NGHI_VIEC, ID_CTL, MS_CTL, ID_LCV , NGAY_CONG_CHUAN, NGAY_CONG_LV,NGAY_VAO_CTY)
	SELECT @TNGAY, T1.ID_DV, T1.ID_XN, T1.ID_TO, T1.ID_CN, T1.ID_TT_HT, T1.NGAY_NGHI_VIEC, ISNULL(T2.ID_CTL,2), CTL.MA_SO, T1.ID_LCV , @NgayCC, @NgayCLV,T1.NGAY_VAO_CTY
	FROM #CN T1 LEFT JOIN #CCTHANG T2 ON T2.ID_CN = T1.ID_CN
				LEFT JOIN dbo.CACH_TINH_LUONG CTL ON CTL.ID_CTL = T2.ID_CTL
	----WHERE (CASE WHEN T1.ID_CV <> 205 THEN 1 ELSE 2 END = @LOAI)


		--Lay thong tin luong cong nhan 
	SELECT T1.ID_CN, ISNULL(T1.MUC_LUONG_THUC,0) MUC_LUONG_THUC INTO #LUONG_HDLD FROM dbo.LUONG_CO_BAN T1 INNER JOIN (SELECT ID_CN, MAX(NGAY_HIEU_LUC) NGAYMAX FROM LUONG_CO_BAN WHERE NGAY_HIEU_LUC <= @DNGAY GROUP BY ID_CN) T2 ON T2.ID_CN = T1.ID_CN AND T1.NGAY_HIEU_LUC = T2.NGAYMAX
	UPDATE T1
	SET LUONG_HDLD = (ISNULL(T2.MUC_LUONG_THUC,0))
	FROM #TBLuongThang T1 LEFT JOIN #LUONG_HDLD T2 ON T2.ID_CN = T1.ID_CN

	--Lay thong tin ngay cong tu cham cong thang de tinh luong
	UPDATE #TBLuongThang SET DL = ROUND(ISNULL(T2.NGAY_CONG,0),1)
	,CN = ROUND(ISNULL(T2.NGAY_CONG_CN,0),1),
	GLT = ROUND(ISNULL(T2.TANG_CA_DEM,0) + ISNULL(T2.TANG_CA_150,0)+ISNULL(T2.TANG_CA_200,0) + ISNULL(T2.TANG_CA_300,0),1),--giờ làm thêm
	TIEN_THEM_GIO = ROUND((LUONG_HDLD/@NgayCLV/8 * ISNULL(T2.TANG_CA_DEM,0) + ISNULL(T2.TANG_CA_150,0) *1.5) + (LUONG_HDLD/@NgayCLV/8 * ISNULL(T2.TANG_CA_200,0) *2.0) + (LUONG_HDLD/@NgayCLV/8 * ISNULL(T2.TANG_CA_300,0) *2.0),1),

	LUONG_PHEP_NGAY = ROUND(ISNULL(T2.NGAY_PHEP,0),1),--Ngày phép
	NGAY_LE = (SELECT COUNT(*) FROM dbo.NGAY_NGHI_LE WHERE MONTH(NGAY) = MONTH(@TNGAY) AND YEAR(NGAY) = YEAR(@TNGAY))
	FROM #TBLuongThang T1 LEFT JOIN #CCTHANG T2 ON T1.ID_CN = T2.ID_CN AND T1.ID_CTL = T2.ID_CTL

	-- get Công vắng
	SELECT T1.ID_CN, T1.ID_LDV ,SUM(T1.CONG_VANG)  CONG_VANG INTO #CONG_VANG
	FROM dbo.CHAM_CONG T1 
	WHERE T1.NGAY BETWEEN @TNGAY AND @DNGAY AND ISNULL(T1.ID_LDV,0) <> 0
	GROUP BY T1.ID_CN, T1.ID_LDV

		-- tính công vắng nghỉ ko lý do
	SELECT T1.ID_CN, T1.CONG_VANG CONG_VANG_KLD INTO #CONG_VANG_KLD FROM #CONG_VANG T1 INNER JOIN dbo.LY_DO_VANG T2 ON T2.ID_LDV = T1.ID_LDV
	WHERE T2.MS_LDV = 'O'

		-- tính công vắng có lý do
	SELECT T1.ID_CN, T1.CONG_VANG CONG_VANG_CLD INTO #CONG_VANG_CLD FROM #CONG_VANG T1 INNER JOIN dbo.LY_DO_VANG T2 ON T2.ID_LDV = T1.ID_LDV
	WHERE T2.MS_LDV <> 'O'

		-- GET danh sách công nhân vi phạm trong tháng
	SELECT ID_CN, NGAY_HIEU_LUC INTO #DSCN_VP FROM dbo.KHEN_THUONG WHERE NGAY_HIEU_LUC BETWEEN @TNGAY AND @DNGAY AND LOAI_KT IN (2,3)


	---cập nhật những tồn tại những cột import vào bảng lương tháng

	

	UPDATE A
	SET A.THUONG_HIEU_SUAT = B.THUONG_HIEU_SUAT,
	A.THUONG_C_HANH = B.THUONG_C_HANH,
	A.THUONG_HTNV =B.THUONG_HTNV,
	A.TRO_CAP_CN =B.TRO_CAP_CN,
	A.TIEN_XANG = B.TIEN_XANG,
	A.THUONG =B.THUONG,
	A.KHAU_TRU_TAM_UNG = B.KHAU_TRU_TAM_UNG,
	A.KHAU_TRU = B.KHAU_TRU
	FROM #TBLuongThang A
	INNER JOIN dbo.BANG_LUONG_TG B ON A.ID_CN = B.ID_CN AND A.THANG = B.THANG



	UPDATE T1
	SET T1.VM = ROUND(ISNULL(T2.CONG_VANG,0),1)
	FROM #TBLuongThang T1 LEFT JOIN #CONG_VANG T2 ON T2.ID_CN = T1.ID_CN


	UPDATE T1
	SET T1.VM = ROUND(ISNULL(T2.CONG_VANG_KLD,0),1)
	FROM #TBLuongThang T1 LEFT JOIN #CONG_VANG_KLD T2 ON T2.ID_CN = T1.ID_CN


	UPDATE #TBLuongThang
	SET LUONG_NGAY_CONG = ROUND(LUONG_HDLD/@NgayCLV * DL,0),
	LUONG_NGAY_CN = ROUND(LUONG_HDLD/@NgayCLV * 2,0),
	LUONG_PHEP_TIEN = ROUND(LUONG_HDLD/26 * LUONG_PHEP_NGAY,0),
	LUONG_LE_TET = 	ROUND(LUONG_HDLD/26 * NGAY_LE,0),
	BHXH_BHTN =  ROUND(LUONG_HDLD * 0.09,0),
	BHYT = ROUND(LUONG_HDLD * 0.015,0)
	--tính bù nhu cầu cơ bảng
	UPDATE #TBLuongThang
	SET BU_NCCB = CASE WHEN	 ISNULL((4700000/26 * DL) - (LUONG_NGAY_CONG + ISNULL(THUONG_HIEU_SUAT,0) + ISNULL(THUONG_C_HANH,0) + LUONG_PHEP_TIEN + LUONG_LE_TET + ISNULL(THUONG_HTNV,0) + ISNULL(TRO_CAP_CN,0) + ISNULL(TIEN_XANG,0) + ISNULL(THUONG,0)),0) > 0 THEN ISNULL((4700000/26 * DL) - (LUONG_NGAY_CONG + ISNULL(THUONG_HIEU_SUAT,0) + ISNULL(THUONG_C_HANH,0) + LUONG_PHEP_TIEN + LUONG_LE_TET + ISNULL(THUONG_HTNV,0) + ISNULL(TRO_CAP_CN,0) + ISNULL(TIEN_XANG,0) + ISNULL(THUONG,0)),0) ELSE 0 END
	--tính Lương cả tháng
	UPDATE #TBLuongThang
	SET LUONG_CA_THANG = (LUONG_NGAY_CONG + TIEN_THEM_GIO + ISNULL(THUONG_HIEU_SUAT,0) + ISNULL(THUONG_C_HANH,0) + LUONG_PHEP_TIEN + LUONG_LE_TET + ISNULL(THUONG_HTNV,0) + ISNULL(TRO_CAP_CN,0) + ISNULL(TIEN_XANG,0) + ISNULL(THUONG,0) + BU_NCCB)

	---tính thuế thu nhập cá nhân
	UPDATE #TBLuongThang
	SET THUE_TNCN = ROUND(((LUONG_CA_THANG - ISNULL(KHAU_TRU_TAM_UNG,0) - BHXH_BHTN - BHYT - ISNULL(KHAU_TRU,0))  - 11000000) * dbo.fnGetPhanTramThueTNCN(((LUONG_CA_THANG - ISNULL(KHAU_TRU_TAM_UNG,0) - BHXH_BHTN - BHYT - ISNULL(KHAU_TRU,0))  - 11000000)) ,0)

		---tính thuế thu nhập cá nhân
	UPDATE #TBLuongThang
	SET THUE_TNCN = CASE WHEN THUE_TNCN > 0 THEN THUE_TNCN ELSE 0 END

	---tính thực lãnh
	UPDATE #TBLuongThang
	SET THUC_LANH = ROUND(LUONG_CA_THANG - ISNULL(KHAU_TRU_TAM_UNG,0) - BHXH_BHTN - BHYT - ISNULL(KHAU_TRU,0) -THUE_TNCN,0)
	
	--delete bảng lương TG với điều kiện tồn tại trong TBLuongThang
	DELETE A
	FROM dbo.BANG_LUONG_TG A
	INNER JOIN #TBLuongThang B ON A.ID_CN = B.ID_CN AND A.THANG = B.THANG

	INSERT INTO dbo.BANG_LUONG_TG
	(THANG,ID_CN,ID_TO,ID_CTL,ID_DV,ID_LCV,ID_XN,ID_TT_HT,NGAY_VAO_CTY,NGAY_NGHI_VIEC,DL,CN,VM,TD,LUONG_HDLD,LUONG_NGAY_CONG,LUONG_NGAY_CN,GLT,TIEN_THEM_GIO,THUONG_HIEU_SUAT,THUONG_C_HANH,LUONG_PHEP_NGAY,LUONG_PHEP_TIEN,NGAY_LE,
LUONG_LE_TET,THUONG_HTNV,TRO_CAP_CN,TIEN_XANG,THUONG,BU_NCCB,LUONG_CA_THANG,KHAU_TRU_TAM_UNG,BHXH_BHTN,BHYT,KHAU_TRU,THUE_TNCN,THUC_LANH,KY_NHAN)
	SELECT THANG, ID_CN, ID_TO, ID_CTL, ID_DV, ID_LCV, ID_XN, ID_TT_HT,NGAY_VAO_CTY,NGAY_NGHI_VIEC,DL,CN,VM,TD,
	LUONG_HDLD,LUONG_NGAY_CONG,
	LUONG_NGAY_CN,--LUONG_NGAY_CN
	GLT,TIEN_THEM_GIO,
	0,0,LUONG_PHEP_NGAY,
	LUONG_PHEP_TIEN,---lương phép
	NGAY_LE,
	LUONG_LE_TET,---lương lể
	0,0,0,0,
	BU_NCCB,--Bù NCCB
	LUONG_NGAY_CN,--Lương cả tháng
	 0,
	 BHXH_BHTN,--BHXH_BHTN
	 BHYT,--BHYT
	 0,
	 THUE_TNCN,
	 THUC_LANH,
	 ''
	FROM #TBLuongThang 
	
	SELECT T2.MS_CN,
                     T1.DL,
                     T1.CN,
                     T1.VM,
                     T1.LUONG_HDLD,
                     T1.LUONG_NGAY_CONG,
                     T1.LUONG_NGAY_CN,
                     T1.GLT,
                     T1.TIEN_THEM_GIO,
                     T1.THUONG_HIEU_SUAT,
                     T1.THUONG_C_HANH,
                     T1.LUONG_PHEP_NGAY,
                     T1.LUONG_PHEP_TIEN,
                     T1.NGAY_LE,
                     T1.LUONG_LE_TET,
                     T1.THUONG_HTNV,
                     T1.TRO_CAP_CN,
                     T1.TIEN_XANG,
                     T1.THUONG,
                     T1.BU_NCCB,
                     T1.LUONG_CA_THANG,
                     T1.KHAU_TRU_TAM_UNG,
                     T1.BHXH_BHTN,
                     T1.BHYT,
                     T1.KHAU_TRU,
                     T1.THUE_TNCN,
                     T1.THUC_LANH,
                     T1.KY_NHAN FROM #TBLuongThang T1 INNER JOIN CONG_NHAN T2 ON T1.ID_CN = T2.ID_CN -- WHERE T1.ID_CN = 6410
	ORDER BY T2.MS_CN
END
GO


