

ALTER PROCEDURE [dbo].[spGetBangLuong_TG]
	@UName NVARCHAR(100) ='admin',
	@NNgu INT =0,
	@DVi INT = -1,
	@XN INT = -1,
	@TO INT = -1,
	@TNGAY Date ='2023-03-01',
	@DNGAY Date ='2023-03-31'
AS 
BEGIN


	
	SELECT * INTO #CN FROM dbo.MGetListNhanSuFormToDate(@UName,@NNgu, @DVi, @XN, @TO, @TNGAY, @DNGAY)
	DECLARE @Chuoi nvarchar(4000)
	DECLARE @COT Int
	DECLARE @TEN_COT nvarchar(100)
	
	SELECT * INTO #BLTHANG FROM dbo.BANG_LUONG_TG WHERE THANG = @TNGAY
	
	SELECT T1.ID_CN, T2.ID_TO ,T1.ID_CTL, T2.MS_CN, T2.HO_TEN, T2.TEN_TO,T4.TEN AS CACH_TL, CASE @NNgu WHEN 0 THEN T6.TEN_LCV ELSE ISNULL(NULLIF(T6.TEN_LCV_A,''),T6.TEN_LCV) END TEN_LCV,
    T1.DL,
    T1.CN,
    T1.VM,
    T1.TD,
    T1.LUONG_HDLD,
    T1.LUONG_NGAY_CONG,
    T1.LUONG_NGAY_CN,
    T1.GLT,
    T1.TIEN_THEM_GIO,
    T1.THUONG_HIEU_SUAT,
    T1.THUONG_C_HANH,
    T1.LUONG_PHEP_NGAY,
    T1.LUONG_PHEP_TIEN,
    T1.NGAY_LE,
    T1.LUONG_LE_TET,
    T1.THUONG_HTNV,
    T1.TRO_CAP_CN,
    T1.TIEN_XANG,
    T1.THUONG,
    T1.BU_NCCB,
    T1.LUONG_CA_THANG,
    T1.KHAU_TRU_TAM_UNG,
    T1.BHXH_BHTN,
    T1.BHYT,
    T1.KHAU_TRU,
    T1.THUE_TNCN,
    T1.THUC_LANH
	FROM #BLTHANG T1 INNER JOIN #CN T2 ON T2.ID_CN = T1.ID_CN
					 INNER JOIN dbo.CHUC_VU T3 ON T3.ID_CV = T2.ID_CV
					 INNER JOIN dbo.CACH_TINH_LUONG T4 ON T4.ID_CTL = T1.ID_CTL
					 LEFT JOIN dbo.LOAI_PHAN_BO T5 ON T5.ID_LPB = T2.PHAN_BO
					 INNER JOIN dbo.LOAI_CONG_VIEC T6 ON T6.ID_LCV = T2.ID_LCV
	WHERE (T2.ID_DV = @DVi OR @DVi = -1) AND (T2.ID_XN = @XN OR @XN = -1) AND (T2.ID_TO = @TO OR @TO = -1)
END
GO

