ALTER PROCEDURE [dbo].[spImportExportLuong_TG]
	@UName NVARCHAR(100) ='admin',
	@NNgu INT =0,
	@DVi INT = -1,
	@XN INT = -1,
	@TO INT = -1,
	@TNGAY Date ='2023-03-01',
	@DNGAY Date ='2023-03-31',
	@SBT NVARCHAR(250) ='sBTLuongCN0',
	@iLoai INT  = 2 ---export,import 

AS 
BEGIN
	DECLARE @NgayBD Date
	DECLARE @NgayKT Date
	SET @NgayBD = @TNGAY
	SET @NgayKT = @DNGAY
	SELECT * INTO #CN FROM dbo.MGetListNhanSuFormToDate(@UName,@NNgu, @DVi, @XN, @TO, @TNGAY, @DNGAY)

	IF(@iLoai = 1)
	BEGIN
	--lay danh sach cong nhan tinh luong trong gai doan
	SELECT A.MS_CN,A.HO_TEN,ISNULL(B.THUONG_HIEU_SUAT,0) AS THUONG_HIEU_SUAT,ISNULL(B.THUONG_C_HANH,0) AS THUONG_C_HANH,ISNULL(B.THUONG_HTNV,0) AS THUONG_HTNV,
	ISNULL(B.TRO_CAP_CN,0) AS TRO_CAP_CN,ISNULL(B.TIEN_XANG,0) AS TIEN_XANG,ISNULL(B.THUONG,0) AS THUONG,ISNULL(B.KHAU_TRU_TAM_UNG,0) AS KHAU_TRU_TAM_UNG,ISNULL(B.KHAU_TRU,0) AS KHAU_TRU FROM #CN A
	LEFT JOIN (SELECT * FROM dbo.BANG_LUONG_TG  WHERE THANG = @TNGAY) B ON B.ID_CN = A.ID_CN
	END
	IF(@iLoai = 2)
	BEGIN
		CREATE TABLE #TEMPT_LUONGCN (
		[MS_CN] [nvarchar] (200)  NULL,
		[THUONG_HIEU_SUAT] FLOAT NULL,
		[THUONG_C_HANH] FLOAT NULL,
		[THUONG_HTNV] FLOAT NULL,
		[TRO_CAP_CN] FLOAT NULL,
		[TIEN_XANG] FLOAT NULL,
		[THUONG] FLOAT NULL,
		[KHAU_TRU_TAM_UNG] FLOAT NULL,
		[KHAU_TRU] FLOAT NULL
		) ON [PRIMARY]
		DECLARE @sSql nvarchar(4000)
		BEGIN
		set @sSql = 'INSERT INTO #TEMPT_LUONGCN SELECT MS_CN,THUONG_HIEU_SUAT,THUONG_C_HANH,THUONG_HTNV,TRO_CAP_CN,TIEN_XANG,THUONG,KHAU_TRU_TAM_UNG,KHAU_TRU FROM ' + @SBT
		EXEC (@sSql)
		--set @sSql = 'DROP TABLE ' + @SBT
		--EXEC (@sSql)

		INSERT INTO dbo.BANG_LUONG_TG
		(
		    THANG,
		    ID_CN,
		    ID_TO,
		    ID_CTL,
		    ID_DV,
		    ID_LCV,
		    ID_XN,
		    ID_TT_HT,
		    NGAY_VAO_CTY,
		    NGAY_NGHI_VIEC,
			THUONG_HIEU_SUAT,THUONG_C_HANH,THUONG_HTNV,TRO_CAP_CN,TIEN_XANG,THUONG,KHAU_TRU_TAM_UNG,KHAU_TRU
		)
		SELECT @TNGAY, ID_CN,ID_TO,ID_CTL,ID_DV,ID_LCV,ID_XN,ID_TT_HT,NGAY_VAO_CTY,NGAY_NGHI_VIEC,
		THUONG_HIEU_SUAT,THUONG_C_HANH,THUONG_HTNV,TRO_CAP_CN,TIEN_XANG,THUONG,KHAU_TRU_TAM_UNG,KHAU_TRU FROM #TEMPT_LUONGCN A
		INNER JOIN #CN B ON B.MS_CN = A.MS_CN
		WHERE NOT EXISTS (SELECT * FROM dbo.BANG_LUONG_TG C WHERE C.THANG = @TNGAY AND C.ID_CN = B.ID_CN)


		UPDATE A
		SET A.THUONG_HIEU_SUAT = B.THUONG_HIEU_SUAT,A.THUONG_C_HANH =B.THUONG_C_HANH,A.THUONG_HTNV =B.THUONG_HTNV,A.TRO_CAP_CN =B.TRO_CAP_CN,A.TIEN_XANG = B.TIEN_XANG,A.THUONG = B.THUONG,A.KHAU_TRU_TAM_UNG = B.KHAU_TRU_TAM_UNG,A.KHAU_TRU =B.KHAU_TRU
		FROM dbo.BANG_LUONG_TG A
		INNER JOIN (SELECT @TNGAY AS THANG, ID_CN,ID_TO,ID_CTL,ID_DV,ID_LCV,ID_XN,ID_TT_HT,NGAY_VAO_CTY,NGAY_NGHI_VIEC,
		THUONG_HIEU_SUAT,THUONG_C_HANH,THUONG_HTNV,TRO_CAP_CN,TIEN_XANG,THUONG,KHAU_TRU_TAM_UNG,KHAU_TRU FROM #TEMPT_LUONGCN T
		INNER JOIN #CN T1 ON T.MS_CN = T1.MS_CN) B ON A.ID_CN = B.ID_CN AND A.THANG = B.THANG

	END
END
END

