
CREATE FUNCTION [dbo].[fnGetLuongHotroKinhNguyet](@IDCN BIGINT, @LCB FLOAT)  
RETURNS FLOAT
AS   
BEGIN
	DECLARE @resulst FLOAT = 0
	IF(SELECT PHAI FROM dbo.CONG_NHAN WHERE ID_CN = @IDCN) =  0
	BEGIN
		IF EXISTS( SELECT * FROM dbo.THEO_DOI_THAI_SAN WHERE ID_CN = @IDCN AND  DATEADD(MONTH,19,NGAY_KINH_CUOI) > GETDATE())
		SET @resulst = 0
		ELSE
        SET @resulst = @LCB /26/ 8 * 1.5
	END
	RETURN @resulst
END; 
GO

