
ALTER PROCEDURE [dbo].[rptBangLuongThang_TG]
	@UName NVARCHAR(100) ='admin',
	@NNgu INT =0,
	@DVi INT = -1,
	@XN INT = -1,
	@TO INT = -1,
	@Thang DateTime = '20230301'
AS 
BEGIN
		SELECT * INTO #CN FROM dbo.MGetListNhanSuFormToDate(@UName,@NNgu, @DVi, @XN, @TO, @Thang, DATEADD(DAY,-1,DATEADD(MONTH,1,@Thang)))

	SELECT ROW_NUMBER() OVER(ORDER BY B.MS_CN) AS STT, B.MS_CN, B.HO_TEN,
	A.DL,
	A.CN,
	A.VM,
	A.TD,
	A.LUONG_HDLD,
	A.LUONG_NGAY_CN,
	A.GLT,
	A.TIEN_THEM_GIO,
	A.THUONG_HIEU_SUAT,
	A.THUONG_C_HANH,
	A.LUONG_PHEP_NGAY,
	A.LUONG_PHEP_TIEN,
	A.NGAY_LE,
	A.LUONG_LE_TET,
	A.THUONG_HTNV,
	A.TRO_CAP_CN,
	A.TIEN_XANG,
	A.THUONG,
	A.BU_NCCB,
	A.LUONG_CA_THANG,
	A.KHAU_TRU_TAM_UNG,
	A.BHXH_BHTN,
	A.BHYT,
	A.KHAU_TRU,
	A.THUE_TNCN,
	A.THUC_LANH,
	 '' AS  KY_NHAN
	FROM dbo.BANG_LUONG_TG A
	INNER JOIN #CN B ON B.ID_CN = A.ID_CN AND A.THANG = @Thang
END
GO

