ALTER PROCEDURE [dbo].[spGetListHopDong]
	@ID_CN BIGINT =303,
	@UName NVARCHAR(100) ='admin',
	@NNgu INT =0
AS
BEGIN
SELECT
	A.ID_HDLD,
	SO_HDLD ,
	STT_HDLD ,
	A.ID_LHDLD ,
	CASE @NNgu WHEN 0 THEN B.TEN_LHDLD WHEN 1 THEN ISNULL(NULLIF(B.TEN_LHDLD_A,''),B.TEN_LHDLD) ELSE ISNULL(NULLIF(B.TEN_LHDLD_H,''),B.TEN_LHDLD) END AS TEN_LHDLD,
	NGAY_BAT_DAU_HD ,
	NGAY_HET_HD ,
	NGAY_KY ,
	HD_GIA_HAN ,
	NGAY_BD_THU_VIEC ,
	NGAY_KT_THU_VIEC ,
	LUONG_THU_VIEC ,
	BAC_LUONG ,
	(SELECT TOP 1 ID_NL FROM dbo.BAC_LUONG WHERE ID_BL = BAC_LUONG) AS NGACH_LUONG,
	ISNULL(MUC_LUONG_CHINH,0) MUC_LUONG_CHINH ,
	ISNULL(CHI_SO_PHU_CAP,0) CHI_SO_PHU_CAP ,
	ISNULL(MUC_LUONG_THUC_LINH,0) MUC_LUONG_THUC_LINH ,
	DIA_DIEM_LAM_VIEC ,
	CASE @NNgu WHEN 0 THEN A.PHUONG_TIEN ELSE NULLIF(ISNULL(A.PHUONG_TIEN_ENG,''),A.PHUONG_TIEN) END AS PHUONG_TIEN,
	DIA_CHI_NOI_LAM_VIEC ,
	CASE @NNgu WHEN 0 THEN A.PHU_CAP ELSE NULLIF(ISNULL(A.PHU_CAP_ENG,''),A.PHU_CAP) END AS PHU_CAP,
	CONG_VIEC ,
	ID_CV ,
	A.CHE_DO_LAM_VIEC,
	CASE @NNgu WHEN 0 THEN A.LAN_TRA_LUONG ELSE NULLIF(ISNULL(A.LAN_TRA_LUONG_ENG,''),A.LAN_TRA_LUONG) END AS LAN_TRA_LUONG,
	CASE @NNgu WHEN 0 THEN A.DCLD ELSE NULLIF(ISNULL(A.DCLD_ENG,''),A.DCLD) END AS DCLD,
	CASE @NNgu WHEN 0 THEN A.BHLD ELSE NULLIF(ISNULL(A.BHLD_ENG,''),A.BHLD) END AS BHLD,
	A.CHE_DO_DAO_TAO,
	SO_NGAY_PHEP ,
	A.HINH_THUC_TRA_LUONG,
	NGUOI_KY_GIA_HAN,
	A.CHE_DO_NANG_LUONG,
	CASE @NNgu WHEN 0 THEN A.KHOAN_KHAC ELSE NULLIF(ISNULL(A.KHOAN_KHAC_ENG,''),A.KHOAN_KHAC) END AS KHOAN_KHAC,ID_TT,TAI_LIEU
FROM dbo.HOP_DONG_LAO_DONG A
INNER JOIN dbo.LOAI_HDLD B ON B.ID_LHDLD = A.ID_LHDLD
WHERE A.ID_CN =@ID_CN
ORDER BY A.NGAY_BAT_DAU_HD DESC;
END
GO

