
ALTER PROCEDURE [dbo].[spGetComboLDV]
	@Username NVARCHAR(100) ='admin',
	@NNgu INT =0,
	@CoAll BIT=1,
	@TinhBH INT = -1
AS 
BEGIN
IF @CoAll = 1
BEGIN
SELECT * FROM (
SELECT ID_LDV,MS_LDV,CASE @NNgu WHEN 0 THEN TEN_LDV WHEN 1 THEN ISNULL(NULLIF(TEN_LDV_A,''),TEN_LDV) ELSE ISNULL(NULLIF(TEN_LDV_H,''),TEN_LDV) END AS TEN_LDV FROM dbo.LY_DO_VANG WHERE (TINH_BHXH =@TinhBH OR @TinhBH = -1)
UNION 
SELECT -1,'< All >','<All>')T
ORDER BY T.TEN_LDV
END
ELSE
BEGIN
SELECT ID_LDV,MS_LDV,CASE @NNgu WHEN 0 THEN TEN_LDV WHEN 1 THEN ISNULL(NULLIF(TEN_LDV_A,''),TEN_LDV) ELSE ISNULL(NULLIF(TEN_LDV_H,''),TEN_LDV) END AS TEN_LDV FROM dbo.LY_DO_VANG WHERE (TINH_BHXH =@TinhBH OR @TinhBH = -1) ORDER BY TEN_LDV
END	
END	
GO


