
ALTER PROCEDURE [dbo].[spGetListCongTac]
	@ID_CN BIGINT =756,
	@UName NVARCHAR(100) ='admin',
	@NNgu INT =0
AS
BEGIN
	SELECT A.ID_QTCT, A.ID_CN, SO_QUYET_DINH, B.HO +' '+B.TEN AS TEN_CN, ID_LQD, ID_NK,	A.ID_TO, A.ID_CV, A.ID_LCV, ID_TO_CU, 
	ID_CV_CU, ID_LCV_CU, NGAY_KY, NGAY_HIEU_LUC, DVOLD.TEN_NGAN AS TEN_DV,
	CASE @NNgu WHEN 0 THEN XNOLD.TEN_XN WHEN 1 THEN ISNULL(NULLIF(XNOLD.TEN_XN_A,''),XNOLD.TEN_XN) ELSE ISNULL(NULLIF(XNOLD.TEN_XN_H,''),XNOLD.TEN_XN) END AS TEN_XN,
	CASE @NNgu WHEN 0 THEN TOLD.TEN_TO WHEN 1 THEN ISNULL(NULLIF(TOLD.TEN_TO_A,''),TOLD.TEN_TO) ELSE ISNULL(NULLIF(TOLD.TEN_TO_H,''),TOLD.TEN_TO) END AS TEN_TO, 
	NOI_CONG_TAC, NHIEM_VU, MUC_LUONG, MUC_LUONG_CU, XNNEW.ID_XN,
	CASE @NNgu WHEN 0 THEN XNNEW.TEN_XN WHEN 1 THEN ISNULL(NULLIF(XNNEW.TEN_XN_A,''),XNNEW.TEN_XN) ELSE ISNULL(NULLIF(XNNEW.TEN_XN_H,''),XNNEW.TEN_XN) END AS TEN_XN_NEW,
	CASE @NNgu WHEN 0 THEN TNEW.TEN_TO WHEN 1 THEN ISNULL(NULLIF(TNEW.TEN_TO_A,''),TNEW.TEN_TO) ELSE ISNULL(NULLIF(TNEW.TEN_TO_H,''),TNEW.TEN_TO) END AS TEN_TO_NEW, 
	CASE @NNgu WHEN 0 THEN CVNEW.TEN_CV WHEN 1 THEN ISNULL(NULLIF(CVNEW.TEN_CV_A,''),CVNEW.TEN_CV) ELSE ISNULL(NULLIF(CVNEW.TEN_CV_H,''),CVNEW.TEN_CV) END AS TEN_CV_NEW, 
	CASE @NNgu WHEN 0 THEN LCVNEW.TEN_LCV WHEN 1 THEN ISNULL(NULLIF(LCVNEW.TEN_LCV_A,''),LCVNEW.TEN_LCV) ELSE ISNULL(NULLIF(LCVNEW.TEN_LCV_H,''),LCVNEW.TEN_LCV) END AS TEN_LCV_NEW, 

	  DVNEW.ID_DV, A.GHI_CHU,A.ID_CTL_CU,A.ID_CTL
	FROM QUA_TRINH_CONG_TAC A INNER JOIN dbo.CONG_NHAN B ON B.ID_CN = A.ID_CN
	LEFT JOIN dbo.[TO] TOLD ON TOLD.ID_TO = A.ID_TO_CU LEFT JOIN dbo.XI_NGHIEP XNOLD ON XNOLD.ID_XN = TOLD.ID_XN LEFT JOIN dbo.DON_VI DVOLD ON DVOLD.ID_DV = XNOLD.ID_DV
	LEFT JOIN dbo.[TO] TNEW ON TNEW.ID_TO = A.ID_TO LEFT JOIN dbo.XI_NGHIEP XNNEW ON TNEW.ID_XN = XNNEW.ID_XN LEFT JOIN dbo.DON_VI DVNEW ON DVNEW.ID_DV = XNNEW.ID_DV
	LEFT JOIN dbo.CHUC_VU CVNEW ON CVNEW.ID_CV = A.ID_CV LEFT JOIN dbo.LOAI_CONG_VIEC LCVNEW ON LCVNEW.ID_LCV = A.ID_LCV
	WHERE A.ID_CN =@ID_CN
	ORDER BY A.NGAY_HIEU_LUC DESC;
END


GO

