UPDATE dbo.HOP_DONG_LAO_DONG SET BAC_LUONG = NULL
ALTER TABLE dbo.HOP_DONG_LAO_DONG ALTER COLUMN BAC_LUONG BIGINT
GO	
ALTER PROCEDURE [dbo].[spGetComboBacLuong]
	@ID_NL BIGINT = -1,
	@NGAY_QD Date = '07/01/2023',
	@Username NVARCHAR(100) ='admin',
	@NNgu INT =0,
	@CoAll BIT=1
AS 
BEGIN
	SELECT T1.ID_BL, T1.TEN_BL FROM BAC_LUONG T1 INNER JOIN (
		SELECT TEN_BL, MAX(NGAY_QD) NGAY_MAX
		FROM BAC_LUONG WHERE NGAY_QD <= @NGAY_QD AND (ID_NL = @ID_NL OR @ID_NL = -1)
		GROUP BY TEN_BL) T2 ON T1.TEN_BL = T2.TEN_BL AND T1.NGAY_QD = T2.NGAY_MAX
	ORDER BY TEN_BL
END
GO

