IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'spGetComboTinhTrang')
   exec('CREATE PROCEDURE spGetComboTinhTrang AS BEGIN SET NOCOUNT ON; END')
GO
ALTER PROCEDURE [dbo].[spGetComboTinhTrang]
	@Username NVARCHAR(100) ='admin',
	@NNgu INT =0,
	@CoAll BIT=1
	AS 
BEGIN
IF @CoAll = 1
BEGIN
SELECT * FROM (
SELECT ID_TT,CASE @NNgu WHEN 0 THEN TenTT WHEN 1 THEN ISNULL(NULLIF(TenTT_A,''),TenTT) ELSE ISNULL(NULLIF(TenTT_H,''),TenTT) END AS TenTT FROM dbo.TINH_TRANG 
UNION 
SELECT -1,'<All>')T
ORDER BY T.ID_TT
END
ELSE
BEGIN
SELECT ID_TT,CASE @NNgu WHEN 0 THEN TenTT WHEN 1 THEN ISNULL(NULLIF(TenTT_A,''),TenTT) ELSE ISNULL(NULLIF(TenTT_H,''),TenTT) END AS TenTT FROM dbo.TINH_TRANG ORDER BY ID_TT
END	
END	
GO

