
ALTER PROCEDURE [dbo].[spGetListTienLuong]
	@ID_CN BIGINT =303,
	@UName NVARCHAR(100) ='admin',
	@NNgu INT =0
AS
BEGIN
SELECT
	   A.SO_QUYET_DINH ,
	   A.ID_LCB ,
       A.ID_CN ,
       A.ID_TO ,
       A.ID_CV ,
       A.ID_NK ,
	   B.HO_TEN AS NGUOI_KY,
       A.ID_NL ,
	   CASE @NNgu WHEN 0 THEN C.TEN_NL WHEN 1 THEN ISNULL(NULLIF(C.TEN_NL_A,''),C.TEN_NL) ELSE ISNULL(NULLIF(C.TEN_NL_H,''),C.TEN_NL) END AS TEN_NL,
       A.ID_BL ,
	   D.TEN_BL,
       A.NGAY_KY ,
       
       A.NGAY_HIEU_LUC ,
       A.GHI_CHU ,
       A.HS_LUONG ,
       A.LUONG_CO_BAN ,
       A.MUC_LUONG_THUC ,
       A.THUONG_CHUYEN_CAN ,
       A.PC_DOC_HAI ,
       A.THUONG_HT_CV ,
       A.PC_KY_NANG ,
       A.PC_SINH_HOAT,
	   A.PC_CON_NHO,A.ID_TT,A.TAI_LIEU
FROM dbo.LUONG_CO_BAN A
INNER JOIN dbo.NGUOI_KY_GIAY_TO B ON B.ID_NK = A.ID_NK
INNER JOIN dbo.NGACH_LUONG C ON C.ID_NL = A.ID_NL
INNER JOIN dbo.BAC_LUONG D ON D.ID_BL = A.ID_BL
WHERE A.ID_CN = @ID_CN
ORDER BY A.NGAY_HIEU_LUC DESC
END


GO

