ALTER PROCEDURE [dbo].[spGetListKhenThuong]
	@ID_CN BIGINT =-1,
	@UName NVARCHAR(100) ='admin',
	@NNgu INT =0
AS
BEGIN
SELECT ID_KTHUONG ,
       ID_CN ,
       SO_QUYET_DINH ,
       NGAY_HIEU_LUC ,
       NGAY_KY ,
       ID_NK ,
       ID_KT_KL  ,
	   CASE A.ID_KT_KL WHEN 1 THEN CASE @NNgu WHEN 0 THEN N'Khen thưởng' WHEN 1 THEN 'Bonus' ELSE 'Bonus' END WHEN 2 THEN CASE @NNgu WHEN 0 THEN N'Kỷ luật' WHEN 1 THEN 'discipline' ELSE 'discipline' END END AS KT_KL,
       LOAI_KT ,
	   CASE @NNgu WHEN 0 THEN B.TEN_LOAI_KT WHEN 1 THEN ISNULL(NULLIF(B.TEN_LOAI_KT_A,TEN_LOAI_KT),B.TEN_LOAI_KT_A) ELSE ISNULL(NULLIF(B.TEN_LOAI_KT_H,''),B.TEN_LOAI_KT) END AS TEN_LOAI_KT,
       GHI_CHU ,NOI_DUNG, ISNULL(DINH_CHI,0) AS DINH_CHI, A.LAN_CANH_CAO, VP_TRUOC_DO, THOI_HAN_DC, KH_SUA_DOI, THOI_HAN_SD,A.ID_TT,A.TAI_LIEU
	   FROM dbo.KHEN_THUONG A
	   INNER JOIN dbo.LOAI_KHEN_THUONG B ON A.LOAI_KT = B.ID_LOAI_KT
	   WHERE  (ID_CN = @ID_CN OR @ID_CN = -1)   
END
GO

