IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'spGetComboLoaiTuyen')
   exec('CREATE PROCEDURE spGetComboLoaiTuyen AS BEGIN SET NOCOUNT ON; END')
GO
ALTER PROCEDURE [dbo].[spGetComboLoaiTuyen]
	@Username NVARCHAR(100) ='admin',
	@NNgu INT =0,
	@CoAll BIT=1
AS 
BEGIN
IF @CoAll = 1
BEGIN
SELECT * FROM (
SELECT ID_LOAI_TUYEN,TEN_LOAI_TUYEN FROM dbo.YCTD_LOAI_TUYEN
UNION 
SELECT -1,'< All >')T
ORDER BY T.TEN_LOAI_TUYEN
END
ELSE
BEGIN
SELECT ID_LOAI_TUYEN,TEN_LOAI_TUYEN FROM dbo.YCTD_LOAI_TUYEN
ORDER BY TEN_LOAI_TUYEN
END	
END	
GO

