IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'spGetComboKinhNghiemLV')
   exec('CREATE PROCEDURE spGetComboKinhNghiemLV AS BEGIN SET NOCOUNT ON; END')
GO
ALTER PROCEDURE [dbo].[spGetComboKinhNghiemLV]
	@Username NVARCHAR(100) ='admin',
	@NNgu INT =0,
	@CoAll BIT=1
AS 
BEGIN
IF @CoAll = 1
BEGIN
SELECT * FROM (
SELECT ID_KNLV,CASE @NNgu WHEN 0 THEN TEN_KNLV WHEN 1 THEN ISNULL(NULLIF(TEN_KNLV_A,''),TEN_KNLV) ELSE ISNULL(NULLIF(TEN_KNLV_H,''),TEN_KNLV) END AS TEN_KNLV FROM dbo.KINH_NGHIEM_LV
UNION 
SELECT -1,'< All >')T
ORDER BY T.TEN_KNLV
END
ELSE
BEGIN
SELECT ID_KNLV,CASE @NNgu WHEN 0 THEN TEN_KNLV WHEN 1 THEN ISNULL(NULLIF(TEN_KNLV_A,''),TEN_KNLV) ELSE ISNULL(NULLIF(TEN_KNLV_H,''),TEN_KNLV) END AS TEN_KNLV FROM dbo.KINH_NGHIEM_LV
ORDER BY TEN_KNLV
END	
END	

GO

