
IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'spGetListYCTDVT')
   exec('CREATE PROCEDURE spGetListYCTDVT AS BEGIN SET NOCOUNT ON; END')
GO
ALTER PROCEDURE spGetListYCTDVT
    @ID_YCTD  BIGINT,
	@UserName NVARCHAR(500),
	@NNgu INT
AS
BEGIN
    SELECT A.ID_YCTD,A.ID_VTTD AS ID_LCV,A.SL_TUYEN,A.MUC_LUONG_DK,A.NGAY_DI_LAM,A.YEU_CAU,A.ID_NGANH_TD,A.ID_LHCV,A.ID_KNLV,A.ID_LOAI_TUYEN,A.LY_DO_TUYEN,A.DUONG_DAN_TL,A.ID_TTD
	FROM dbo.YCTD_VI_TRI_TUYEN A 
	WHERE A.ID_YCTD =@ID_YCTD
END
GO



