IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = '[spGetComboTinhTrangDuyet]')
   exec('CREATE PROCEDURE [spGetComboTinhTrangDuyet] AS BEGIN SET NOCOUNT ON; END')
GO
ALTER PROCEDURE [dbo].[spGetComboTinhTrangDuyet]
	@Username NVARCHAR(100) ='admin',
	@NNgu INT =0,
	@CoAll BIT=1
AS 
BEGIN
IF @CoAll = 1
BEGIN
SELECT * FROM (
SELECT ID_TTD,TEN_TT_DUYET FROM dbo.TINH_TRANG_DUYET
UNION 
SELECT -1,'< All >')T
ORDER BY T.TEN_TT_DUYET
END
ELSE
BEGIN
SELECT ID_TTD,TEN_TT_DUYET FROM dbo.TINH_TRANG_DUYET
ORDER BY TEN_TT_DUYET
END	
END	

GO

