IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'spSaveYeuCauTuyenDung')
   exec('CREATE PROCEDURE spSaveYeuCauTuyenDung AS BEGIN SET NOCOUNT ON; END')
GO
ALTER PROCEDURE spSaveYeuCauTuyenDung
    @ID_YCTD  BIGINT = -1,
	@MA_YCTD NVARCHAR(50) = 'TP-2022-07-004',
	@ID_TO BIGINT =11,
	@ID_CN	BIGINT = 30,
	@NGAY_YEU_CAU DATETIME ='2022-07-13 16:48:01.200',
	@NGAY_NHAN_DON DATETIME ='2022-07-13 16:48:01.200',
	@GHI_CHU NVARCHAR(250) ='',
	@sBTVT NVARCHAR(250) ='sBTVTAdmin',
	@sBTThayThe NVARCHAR(250) ='sBTThayTheadmin',
	@sBTFile NVARCHAR(250) =''
AS
BEGIN
	BEGIN TRY
	BEGIN TRANSACTION INS_Target
		IF @ID_YCTD = -1
		BEGIN
			--thêm
				INSERT INTO dbo.YEU_CAU_TUYEN_DUNG(MA_YCTD,ID_TO,ID_CN,NGAY_YEU_CAU,NGAY_NHAN_DON,GHI_CHU)
				VALUES(@MA_YCTD,@ID_TO,@ID_CN,@NGAY_YEU_CAU,@NGAY_NHAN_DON,@GHI_CHU)	
				SET @ID_YCTD = SCOPE_IDENTITY()
		END
		ELSE
		BEGIN
				UPDATE dbo.YEU_CAU_TUYEN_DUNG 
				SET ID_TO =@ID_TO,ID_CN =@ID_CN,NGAY_YEU_CAU =@NGAY_YEU_CAU ,NGAY_NHAN_DON = @NGAY_NHAN_DON,GHI_CHU =@GHI_CHU
				WHERE ID_YCTD =@ID_YCTD
		END
		--creare bảng tạm
		CREATE TABLE #TEMPT_VT (
		[ID_YCTD] [bigint] NULL,
		[ID_LCV] [bigint] NULL,
		[SL_TUYEN] [int] NULL,
		[MUC_LUONG_DK] DECIMAL(18,2)  NULL,
		[NGAY_DI_LAM] [datetime] NULL,
		[YEU_CAU] [nvarchar] (250)  NULL,
		[ID_NGANH_TD] [bigint] NULL,
		[ID_LHCV] [bigint] NULL,
		[ID_KNLV] [bigint] NULL,
		[ID_LOAI_TUYEN] [bigint] NULL,
		[LY_DO_TUYEN] [nvarchar] (250)  NULL,
		[DUONG_DAN_TL] [nvarchar] (250)  NULL,
		[ID_TTD] [bigint] NULL
		) ON [PRIMARY]
		DECLARE @sSql nvarchar(4000)
	
		set @sSql = 'INSERT INTO #TEMPT_VT(ID_YCTD,ID_LCV,SL_TUYEN,MUC_LUONG_DK,NGAY_DI_LAM,YEU_CAU,ID_NGANH_TD,ID_LHCV,ID_KNLV,ID_LOAI_TUYEN,LY_DO_TUYEN,DUONG_DAN_TL,ID_TTD) 
		SELECT '+ CONVERT(NVARCHAR(10),@ID_YCTD) +', ID_LCV,SL_TUYEN,MUC_LUONG_DK,NGAY_DI_LAM,YEU_CAU,ID_NGANH_TD,ID_LHCV,ID_KNLV,ID_LOAI_TUYEN,LY_DO_TUYEN,DUONG_DAN_TL,ID_TTD FROM ' + @sBTVT 
		EXEC (@sSql)


		set @sSql = 'DROP TABLE ' + @sBTVT
		EXEC (@sSql)

		DELETE YCTD_VI_TRI_TUYEN WHERE ID_YCTD = @ID_YCTD 
		INSERT INTO dbo.YCTD_VI_TRI_TUYEN(ID_YCTD,ID_VTTD,ID_TTD,SL_TUYEN,MUC_LUONG_DK,NGAY_DI_LAM,YEU_CAU,ID_NGANH_TD,ID_LHCV,ID_KNLV,ID_LOAI_TUYEN,LY_DO_TUYEN,DUONG_DAN_TL)
		SELECT ID_YCTD,A.ID_LCV,ID_TTD,SL_TUYEN,MUC_LUONG_DK,NGAY_DI_LAM,YEU_CAU,ID_NGANH_TD,ID_LHCV,ID_KNLV,ID_LOAI_TUYEN,LY_DO_TUYEN,DUONG_DAN_TL 
		FROM #TEMPT_VT A WHERE A.ID_YCTD = @ID_YCTD

		CREATE TABLE #TEMPT_ThayThe (
		[ID_YCTD] [bigint] NULL,
		[ID_VTTD] [bigint] NULL,
		[ID_CN] [bigint] NULL,
		[ID_LCV] [bigint] NULL,
		[NGAY_LV_CUOI] [datetime] NULL,
		[LY_DO_NGHI] [nvarchar] (250) NULL
		) ON [PRIMARY]
				set @sSql = 'INSERT INTO #TEMPT_ThayThe(ID_YCTD,ID_VTTD,ID_CN,ID_LCV,NGAY_LV_CUOI,LY_DO_NGHI)
		SELECT '+CONVERT(NVARCHAR(10),@ID_YCTD)+', ID_VTTD,ID_CN,ID_LCV,NGAY_LV_CUOI,LY_DO_NGHI FROM ' + @sBTThayThe
		EXEC (@sSql)
		set @sSql = 'DROP TABLE ' + @sBTThayThe
		EXEC (@sSql)

		
		--insert thay thế chưa tồn tại trong chính
		DELETE YCTD_THAY_THE_CN WHERE ID_YCTD = @ID_YCTD
		INSERT INTO dbo.YCTD_THAY_THE_CN(ID_YCTD,ID_VTTD,ID_CN,ID_LCV,NGAY_LV_CUOI,LY_DO_NGHI)
		SELECT ID_YCTD,ID_VTTD,ID_CN,ID_LCV,NGAY_LV_CUOI,LY_DO_NGHI
		FROM #TEMPT_ThayThe A WHERE A.ID_VTTD IN (SELECT ID_LCV FROM #TEMPT_VT) AND ID_YCTD = @ID_YCTD

		IF @sBTFile != '' 
		BEGIN
			CREATE TABLE #TEMPT_File(
			[ID_YCTD] [bigint] NULL,
			[ID_VT_FL] [bigint] NULL,
			[DUONG_DAN] [nvarchar] (250) NULL,
			[MO_TA] [nvarchar] (250)  NULL,
			[GHI_CHU] [nvarchar] (250)  NULL
			) ON [PRIMARY]
			set @sSql = 'INSERT INTO #TEMPT_File(ID_YCTD,ID_VT_FL,DUONG_DAN,MO_TA,GHI_CHU)
			SELECT '+CONVERT(NVARCHAR(10),@ID_YCTD)+',ID_VT_FL,DUONG_DAN,MO_TA,GHI_CHU FROM ' + @sBTFile
			EXEC (@sSql)
			set @sSql = 'DROP TABLE ' + @sBTFile
			EXEC (@sSql)

					
			DELETE A
			FROM dbo.VI_TRI_FILE A
		    WHERE NOT EXISTS (SELECT * FROM #TEMPT_File B WHERE B.ID_VT_FL = A.ID_VT_FL AND B.ID_YCTD = A.ID_YCTD) AND A.ID_YCTD = @ID_YCTD	
			DBCC CHECKIDENT (LOAI_XEP_LOAI,RESEED,0)
		    DBCC CHECKIDENT (LOAI_XEP_LOAI,RESEED)

			INSERT INTO dbo.VI_TRI_FILE(ID_YCTD,PATH,MO_TA,GHI_CHU)
			SELECT ID_YCTD,A.DUONG_DAN,MO_TA,GHI_CHU  FROM #TEMPT_File A 
			WHERE NOT EXISTS (SELECT * FROM dbo.VI_TRI_FILE B WHERE A.ID_VT_FL = B.ID_VT_FL AND A.ID_YCTD = B.ID_YCTD)

			UPDATE A
			SET A.PATH = B.DUONG_DAN,
			A.MO_TA = B.MO_TA,
			A.GHI_CHU = B.GHI_CHU
			FROM dbo.VI_TRI_FILE A
			INNER JOIN #TEMPT_File B ON B.ID_VT_FL = A.ID_VT_FL AND B.ID_YCTD = A.ID_YCTD
		END
		
		COMMIT TRANSACTION INS_Target
		SELECT @ID_YCTD
	END TRY
	BEGIN CATCH
		SELECT -1
		ROLLBACK TRANSACTION INS_Target
	END CATCH
END
GO
