IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'spGetComboKeHoachPV')
   exec('CREATE PROCEDURE spGetComboKeHoachPV AS BEGIN SET NOCOUNT ON; END')
GO
ALTER PROCEDURE [dbo].[spGetComboKeHoachPV]
	@CoAll BIT=1
AS 
BEGIN
IF @CoAll = 1
BEGIN
SELECT * FROM (
SELECT ID_KHPV,SO_KHPV    FROM dbo.KE_HOACH_PHONG_VAN 
UNION 
SELECT -1,'< All >')T
ORDER BY T.SO_KHPV
END
ELSE
BEGIN
SELECT ID_KHPV,SO_KHPV    FROM dbo.KE_HOACH_PHONG_VAN 
ORDER BY SO_KHPV
END	
END	
GO

