IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'spGetListKeHoachTuyenDung')
   exec('CREATE PROCEDURE spGetListKeHoachTuyenDung AS BEGIN SET NOCOUNT ON; END')
GO
ALTER PROCEDURE spGetListKeHoachTuyenDung
   @TNgay DATETIME = '2022-07-01 11:45:30.833',
   @DNgay DATETIME ='2022-07-15 11:45:30.833',
   @UserName NVARCHAR(50) ='admin',
   @NNgu INT = 0,
   @sBTTuan NVARCHAR(500) ='sBTTuanAdmin'
AS
BEGIN

	SELECT * INTO #TMPCN  FROM  dbo.MGetListNhanSuFormToDate(@UserName,@NNgu,-1,-1,-1,GETDATE(),GETDATE())
	SELECT A.ID_YCTD,B.ID_VTTD,A.MA_YCTD,C.TEN_LCV,TEN_CV,(SELECT COUNT(*) 
	FROM #TMPCN WHERE ID_LCV = B.ID_VTTD) AS SL_HC,B.SL_TUYEN,E.TEN_TO,B.NGAY_DI_LAM,ISNULL(B.LY_DO_TUYEN,(SELECT TEN_LOAI_TUYEN FROM dbo.YCTD_LOAI_TUYEN WHERE ID_LOAI_TUYEN = B.ID_LOAI_TUYEN)) AS LY_DO_TUYEN 
	INTO #TMP
	FROM dbo.YEU_CAU_TUYEN_DUNG A
	INNER JOIN dbo.YCTD_VI_TRI_TUYEN B ON B.ID_YCTD = A.ID_YCTD --AND B.ID_TTD =1
	INNER JOIN dbo.LOAI_CONG_VIEC C ON C.ID_LCV = B.ID_VTTD
	LEFT JOIN dbo.CHUC_VU D ON D.ID_CV = C.ID_CV
	INNER JOIN  dbo.[TO] E ON E.ID_TO = A.ID_TO
	WHERE A.NGAY_YEU_CAU BETWEEN @TNgay AND @DNgay OR B.NGAY_DI_LAM BETWEEN @TNgay AND @DNgay OR (A.NGAY_YEU_CAU < @TNgay AND B.NGAY_DI_LAM > @DNgay)
	ORDER BY A.MA_YCTD,C.TEN_LCV

	SELECT * FROM #TMP

	CREATE TABLE #TEMTUAN(
	[Tuan] [int] NULL,
	[TNgay] [datetime] NULL,
	[DNgay] [datetime] NULL
	) ON [PRIMARY]

	DECLARE @sSql NVARCHAR(1000)
	set @sSql = 'INSERT INTO #TEMTUAN(Tuan,TNgay,DNgay) SELECT Tuan,TNgay,DNgay FROM ' + @sBTTuan
	EXEC (@sSql)
	--set @sSql = 'DROP TABLE ' + @sBTTuan
	--EXEC (@sSql)	

	SELECT ID_YCTD,ID_VTTD,@TNgay AS THANG,B.Tuan AS TUAN,N'Tuần '+ CAST(B.Tuan AS NCHAR(1)) AS TEN_TUAN,B.TNgay,B.DNgay,0 AS SL_KH,'' Note FROM #TMP A
	INNER JOIN #TEMTUAN B ON 1= 1
	WHERE NOT EXISTS (SELECT * FROM KHTD_TUAN C WHERE A.ID_YCTD = C.ID_YCTD AND A.ID_VTTD = C.ID_VTTD AND RIGHT(CONVERT(NVARCHAR(12),B.TNgay,103),7) =RIGHT(CONVERT(NVARCHAR(12),@TNgay,103),7) AND B.Tuan = C.TUAN )
	UNION 
	SELECT ID_YCTD,ID_VTTD,THANG,TUAN,N'Tuần '+ CAST(TUAN AS NCHAR(1)) AS TEN_TUAN,TU_NGAY,DEN_NGAY,SL_KH,Note FROM dbo.KHTD_TUAN 
	WHERE RIGHT(CONVERT(NVARCHAR(12),THANG,103),7) =RIGHT(CONVERT(NVARCHAR(12),@TNgay,103),7)
	ORDER BY ID_YCTD,ID_VTTD,THANG,B.Tuan

	--WHERE NOT EXISTS (SELECT * FROM dbo.KHTD_TUAN C WHERE RIGHT(CONVERT(NVARCHAR(12),B.TNgay,103),7) =RIGHT(CONVERT(NVARCHAR(12),@TNgay,103),7) )
	SELECT A.ID_YCTD,
           A.ID_VTTD,
           ID_NTD,
           Ghi_Chu FROM dbo.KHTD_NTD A
		   INNER JOIN #TMP B ON B.ID_VTTD = A.ID_VTTD AND B.ID_YCTD = A.ID_YCTD


END
GO
