
ALTER PROCEDURE [dbo].[spGetKeHoachTD]
@UName NVARCHAR(50) = 'admin',
@NNgu INT = 0 
AS
BEGIN
	SELECT ID_TB ID_KHTD, SO_TB SO_QD, TIEU_DE, NGAY_LAP, PV_ON_OF_LINE PV_ONLINE, NGAY_PV_ONLINE_DK NGAY_PV_ONLINE, PV_ON_OF_LINE PV_OFFLINE, NGAY_PV_OFLINE_DK NGAY_PV_OFFLINE, VTTD.TEN_LCV, TINH_TRANG
	FROM KE_HOACH_TUYEN_DUNG KHTD INNER JOIN dbo.YEU_CAU_TUYEN_DUNG YCTD ON KHTD.ID_YCTD = YCTD.ID_YCTD
	INNER JOIN dbo.YCTD_VI_TRI_TUYEN VT ON VT.ID_YCTD = YCTD.ID_YCTD
	 LEFT JOIN dbo.LOAI_CONG_VIEC VTTD ON VT.ID_VTTD = VTTD.ID_LCV
END
GO
