IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'spGetComboTinhTrangYC')
   exec('CREATE PROCEDURE spGetComboTinhTrangYC AS BEGIN SET NOCOUNT ON; END')
GO
ALTER PROCEDURE [dbo].[spGetComboTinhTrangYC]
	@Username NVARCHAR(100) ='admin',
	@NNgu INT =0,
	@CoAll BIT=0
AS 
BEGIN
IF @CoAll = 1
BEGIN
SELECT * FROM (
SELECT ID_TTYC,CASE @NNgu WHEN 0 THEN Ten_TTYC WHEN 1 THEN ISNULL(NULLIF(Ten_TTYC_A,''),Ten_TTYC) ELSE ISNULL(NULLIF(Ten_TTYC_H,''),Ten_TTYC) END AS Ten_TTYC FROM dbo.TINH_TRANG_YC
UNION 
SELECT -1,'< All >')T
ORDER BY T.Ten_TTYC
END
ELSE
BEGIN
SELECT ID_TTYC,CASE @NNgu WHEN 0 THEN Ten_TTYC WHEN 1 THEN ISNULL(NULLIF(Ten_TTYC_A,''),Ten_TTYC) ELSE ISNULL(NULLIF(Ten_TTYC_H,''),Ten_TTYC) END AS Ten_TTYC FROM dbo.TINH_TRANG_YC
ORDER BY Ten_TTYC
END	
END	
GO

