
IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'spGetComboYeuCauTD')
   exec('CREATE PROCEDURE spGetComboYeuCauTD AS BEGIN SET NOCOUNT ON; END')
GO
ALTER PROCEDURE [dbo].[spGetComboYeuCauTD]
	@Username NVARCHAR(100) ='admin',
	@NNgu INT =0,
	@CoAll BIT=0,
	@TT INT = 1
AS 
BEGIN
IF @CoAll = 1
BEGIN
SELECT * FROM (
SELECT ID_YCTD,MA_YCTD FROM dbo.YEU_CAU_TUYEN_DUNG WHERE ISNULL(ID_TT,1) = @TT
UNION 
SELECT -1,'< All >')T
ORDER BY T.MA_YCTD
END
ELSE
BEGIN
SELECT ID_YCTD,MA_YCTD FROM dbo.YEU_CAU_TUYEN_DUNG WHERE ISNULL(ID_TT,1) = @TT
ORDER BY MA_YCTD
END	
END	
GO

