IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'spGetComboTinhTrangTD')
   exec('CREATE PROCEDURE spGetComboTinhTrangTD AS BEGIN SET NOCOUNT ON; END')
GO

ALTER PROCEDURE [dbo].[spGetComboTinhTrangTD]
	@Username NVARCHAR(100) ='admin',
	@NNgu INT =0,
	@CoAll BIT=0
AS 
BEGIN
IF @CoAll = 1
BEGIN
SELECT * FROM (
SELECT ID_TTTD,CASE @NNgu WHEN 0 THEN Ten_TTTD WHEN 1 THEN ISNULL(NULLIF(Ten_TTTD_A,''),Ten_TTTD) ELSE ISNULL(NULLIF(Ten_TTTD_H,''),Ten_TTTD) END AS Ten_TTTD FROM dbo.TINH_TRANG_TD
UNION 
SELECT -1,'< All >')T
ORDER BY T.Ten_TTTD
END
ELSE
BEGIN
SELECT ID_TTTD,CASE @NNgu WHEN 0 THEN Ten_TTTD WHEN 1 THEN ISNULL(NULLIF(Ten_TTTD_A,''),Ten_TTTD) ELSE ISNULL(NULLIF(Ten_TTTD_H,''),Ten_TTTD) END AS Ten_TTTD FROM dbo.TINH_TRANG_TD
ORDER BY Ten_TTTD
END	
END	
GO

