IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'spGetListUngVienPV')
   exec('CREATE PROCEDURE spGetListUngVienPV AS BEGIN SET NOCOUNT ON; END')
GO
ALTER PROCEDURE spGetListUngVienPV
	@ID_KHPV BIGINT = 0,
	@UName NVARCHAR(100) ='Admin',  
	@NNgu INT =0 
AS	
BEGIN
	SELECT ID_KHPV,ID_YCTD,ID_VTTD,A.ID_UV,HO +' '+B.TEN AS HO_TEN,A.GHI_CHU,NGUOI_YCTD_CHON FROM dbo.UNG_VIEN_TUYEN_DUNG A
	INNER JOIN dbo.UNG_VIEN B ON B.ID_UV = A.ID_UV
	WHERE A.ID_KHPV = @ID_KHPV
END
GO
