

ALTER PROCEDURE [dbo].[spGetKeHoachTD]
@ID_UV BIGINT = 0,
@UName NVARCHAR(50) = 'admin',
@NNgu INT = 0
AS
BEGIN
	SELECT A.SO_KHPV, TIEU_DE, NGAY_LAP,A.NGUOI_PV_1,A.NGUOI_PV_2,A.NGAY_PV,
	CASE @NNgu WHEN 0 THEN C.TEN_TT_KHPV WHEN 1 THEN ISNULL(NULLIF(C.TEN_TT_KHPV_A,''),TEN_TT_KHPV) ELSE ISNULL(NULLIF(C.TEN_TT_KHPV_H,''),TEN_TT_KHPV) END AS TEN_TT_KHPV
	FROM dbo.KE_HOACH_PHONG_VAN A
	INNER JOIN dbo.UNG_VIEN_TUYEN_DUNG B ON B.ID_KHPV = A.ID_KHPV
	LEFT JOIN dbo.TINH_TRANG_KHPV C ON C.ID_TT_KHPV = A.TINH_TRANG
	WHERE B.ID_UV = @ID_UV
	ORDER BY A.SO_KHPV,A.NGAY_LAP
END
GO


