
ALTER PROCEDURE [dbo].[spUpdateUngVien]
	@ID_UV BIGINT,
	@MS_UV nvarchar(50),
	@HINH_UV  IMAGE,
	@HO  nvarchar(50),
	@TEN  nvarchar(20),
	@NGAY_SINH  DATETIME,
	@PHAI  BIT,
	@HINH_THUC_TUYEN  BIGINT,
	@GHI_CHU  nvarchar(250),
	@ID_DT  BIGINT,
	@NOI_SINH  nvarchar(250),
	@SO_CMND  nvarchar(15),
	@NGAY_CAP  DATETIME,
	@NOI_CAP  nvarchar(150),
	@ID_TT_HN  BIGINT,
	@HO_TEN_VC  nvarchar(50),
	@NGHE_NGHIEP_VC  nvarchar(150),
	@SO_CON  INT,
	@DT_DI_DONG  nvarchar(20),
	@EMAIL  nvarchar(250),
	@DIA_CHI_THUONG_TRU  nvarchar(250),
	@ID_TP  BIGINT,
	@ID_QUAN  BIGINT,
	@ID_PX  BIGINT,
	@THON_XOM  nvarchar(100),
	@ID_TDVH  BIGINT,
	@ID_KNLV  BIGINT,
	@ID_NTD  BIGINT,
	@VI_TRI_TD_1  BIGINT,
	@VI_TRI_TD_2  BIGINT,
	@MUC_LUONG_MONG_MUON  nvarchar(50),
	@NGAY_CO_THE_DI_LAM  DATETIME,
	@NGUOI_LIEN_HE  nvarchar(50),
	@QUAN_HE  nvarchar(50),
	@DT_NGUOI_LIEN_HE  nvarchar(20),
	@ID_CN  BIGINT,
	@DA_GIOI_THIEU  BIT,
	@NGAY_NHAN_VIEC  DATETIME,
	@NGAY_HEN_DI_LAM  DATETIME,
	@XAC_NHAN_DL  BIT,
	@HUY_TUYEN_DUNG  bit,
	@DA_CHUYEN  bit,
	@ID_DGTN INT,
	@XAC_NHAN_DTDH  BIT,
	@Them BIT,
	@sBTBC NVARCHAR(250),
	@sBTKNLV NVARCHAR(250),
	@sBTTTK NVARCHAR(250)
AS
    BEGIN
		IF(@Them = 1)
			BEGIN
				INSERT INTO dbo.UNG_VIEN(MS_UV,HINH_UV,HO,TEN,NGAY_SINH,PHAI,HINH_THUC_TUYEN,GHI_CHU,ID_DT,NOI_SINH,SO_CMND,NGAY_CAP,NOI_CAP,ID_TT_HN,HO_TEN_VC,NGHE_NGHIEP_VC,SO_CON,
				DT_DI_DONG,EMAIL,DIA_CHI_THUONG_TRU,ID_TP,ID_QUAN,ID_PX,THON_XOM,ID_TDVH,ID_KNLV,ID_NTD,VI_TRI_TD_1,VI_TRI_TD_2,MUC_LUONG_MONG_MUON,NGAY_CO_THE_DI_LAM,NGUOI_LIEN_HE,
				QUAN_HE,DT_NGUOI_LIEN_HE,ID_CN,DA_GIOI_THIEU,NGAY_NHAN_VIEC,NGAY_HEN_DI_LAM,XAC_NHAN_DL,HUY_TUYEN_DUNG,DA_CHUYEN,ID_DGTN,XAC_NHAN_DTDH)
				VALUES
				(@MS_UV,@HINH_UV,@HO,@TEN,@NGAY_SINH,@PHAI,@HINH_THUC_TUYEN,@GHI_CHU,@ID_DT,@NOI_SINH,@SO_CMND,@NGAY_CAP,@NOI_CAP,@ID_TT_HN,@HO_TEN_VC,@NGHE_NGHIEP_VC,@SO_CON,
				@DT_DI_DONG,@EMAIL,@DIA_CHI_THUONG_TRU,@ID_TP,@ID_QUAN,@ID_PX,@THON_XOM,@ID_TDVH,@ID_KNLV,@ID_NTD,@VI_TRI_TD_1,@VI_TRI_TD_2,@MUC_LUONG_MONG_MUON,@NGAY_CO_THE_DI_LAM,@NGUOI_LIEN_HE,
				@QUAN_HE,@DT_NGUOI_LIEN_HE,@ID_CN,@DA_GIOI_THIEU,@NGAY_NHAN_VIEC,@NGAY_HEN_DI_LAM,@XAC_NHAN_DL,@HUY_TUYEN_DUNG,@DA_CHUYEN,@ID_DGTN,@XAC_NHAN_DTDH)
				SET @ID_UV = SCOPE_IDENTITY()
			END
		ELSE
			BEGIN
				UPDATE dbo.UNG_VIEN SET MS_UV =	@MS_UV,HINH_UV =	@HINH_UV,HO =	@HO,TEN =	@TEN,NGAY_SINH =	@NGAY_SINH,PHAI =	@PHAI,HINH_THUC_TUYEN =	@HINH_THUC_TUYEN,GHI_CHU =	@GHI_CHU,ID_DT =	@ID_DT,
				NOI_SINH =	@NOI_SINH,SO_CMND =	@SO_CMND,NGAY_CAP =	@NGAY_CAP,NOI_CAP =	@NOI_CAP,ID_TT_HN =	@ID_TT_HN,HO_TEN_VC =	@HO_TEN_VC,NGHE_NGHIEP_VC =	@NGHE_NGHIEP_VC,SO_CON =	@SO_CON,DT_DI_DONG =	@DT_DI_DONG,
				EMAIL =	@EMAIL,DIA_CHI_THUONG_TRU =	@DIA_CHI_THUONG_TRU,ID_TP =	@ID_TP,ID_QUAN =	@ID_QUAN,ID_PX =	@ID_PX,THON_XOM =	@THON_XOM,ID_TDVH =	@ID_TDVH,ID_KNLV =	@ID_KNLV,ID_NTD =	@ID_NTD,
				VI_TRI_TD_1 =	@VI_TRI_TD_1,VI_TRI_TD_2 =	@VI_TRI_TD_2,MUC_LUONG_MONG_MUON =	@MUC_LUONG_MONG_MUON,NGAY_CO_THE_DI_LAM =	@NGAY_CO_THE_DI_LAM,NGUOI_LIEN_HE =	@NGUOI_LIEN_HE,QUAN_HE =	@QUAN_HE,
				DT_NGUOI_LIEN_HE =	@DT_NGUOI_LIEN_HE,ID_CN =	@ID_CN,DA_GIOI_THIEU =	@DA_GIOI_THIEU,NGAY_NHAN_VIEC =	@NGAY_NHAN_VIEC,NGAY_HEN_DI_LAM =	@NGAY_HEN_DI_LAM,XAC_NHAN_DL =	@XAC_NHAN_DL,HUY_TUYEN_DUNG =	@HUY_TUYEN_DUNG,
				DA_CHUYEN =	@DA_CHUYEN,ID_DGTN =@ID_DGTN,XAC_NHAN_DTDH = @XAC_NHAN_DTDH WHERE ID_UV =@ID_UV
			END
		
		CREATE TABLE #sBTBC(
		[ID_BC] [bigint] NULL,
		[ID_UV] [bigint] NULL,
		[TEN_BANG] [nvarchar] (200)  NULL,
		[TEN_TRUONG] [nvarchar] (250) NULL,
		[TU_NAM] [int] NULL,
		[DEN_NAM] [int] NULL,
		[ID_XL] [bigint] NULL
		) ON [PRIMARY]
		
		DECLARE @sSQL NVARCHAR(1000)
		SET @sSQL = 'INSERT INTO #sBTBC (ID_BC,ID_UV,TEN_BANG,TEN_TRUONG,TU_NAM,DEN_NAM,ID_XL) SELECT ID_BC,'+ CONVERT(NVARCHAR(10),@ID_UV) +',TEN_BANG,TEN_TRUONG,TU_NAM,DEN_NAM,ID_XL FROM ' + @sBTBC 
		EXEC(@sSQL)
		SET @sSQL = 'DROP TABLE ' + @sBTBC  
		EXEC(@sSQL)
		 CREATE TABLE #sBTKNLV
		(
		[ID_KN] [bigint] NULL,
		[ID_UV] [bigint] NULL,
		[TEN_CONG_TY] [NVARCHAR](250)  NULL,
		[CHUC_VU] [nvarchar] (100)  NULL,
		[MUC_LUONG] [nvarchar] (50)  NULL,
		[TU_NAM] [int] NULL,
		[DEN_NAM] [int] NULL,
		[LD_NGHI_VIEC] [NVARCHAR](250)  NULL
		) ON [PRIMARY]
	
		SET @sSQL = 'INSERT INTO #sBTKNLV(ID_KN,ID_UV,TEN_CONG_TY,CHUC_VU,MUC_LUONG,TU_NAM,DEN_NAM,LD_NGHI_VIEC) SELECT ID_KN,'+ CONVERT(NVARCHAR(10),@ID_UV) +',TEN_CONG_TY,CHUC_VU,MUC_LUONG,TU_NAM,DEN_NAM,LD_NGHI_VIEC FROM ' + @sBTKNLV 
		EXEC(@sSQL)
		SET @sSQL = 'DROP TABLE ' + @sBTKNLV  
		EXEC(@sSQL)

		CREATE TABLE #sBTTTK
		(
		[ID_TTK] [bigint] NULL,
		[ID_UV] [bigint] NULL,
		[NOI_DUNG] [nvarchar] (250)  NULL,
		[ID_XL] [bigint] NULL
		) ON [PRIMARY]
		
		SET @sSQL = 'INSERT INTO #sBTTTK(ID_TTK,ID_UV,NOI_DUNG,ID_XL) SELECT ID_TTK,'+ CONVERT(NVARCHAR(10),@ID_UV) +',NOI_DUNG,ID_XL FROM ' + @sBTTTK 
		EXEC(@sSQL)
		SET @sSQL = 'DROP TABLE ' + @sBTTTK  
		EXEC(@sSQL)
		--edit bằng cấp

		DELETE  A FROM dbo.UNG_VIEN_BANG_CAP A WHERE ID_UV = @ID_UV AND NOT EXISTS (SELECT * FROM #sBTBC B WHERE A.ID_UV = B.ID_UV AND A.ID_BC = B.ID_BC)
		DBCC CHECKIDENT (UNG_VIEN_BANG_CAP,RESEED,0)
		DBCC CHECKIDENT (UNG_VIEN_BANG_CAP,RESEED)

		UPDATE A
		SET A.TEN_BANG = B.TEN_BANG,A.TEN_TRUONG = B.TEN_TRUONG,A.TU_NAM = B.TU_NAM,A.DEN_NAM =B.DEN_NAM,A.ID_XL =B.ID_XL
		FROM dbo.UNG_VIEN_BANG_CAP A
		INNER JOIN #sBTBC B ON B.ID_UV = A.ID_UV AND B.ID_BC = A.ID_BC

		INSERT INTO UNG_VIEN_BANG_CAP(ID_UV,TEN_BANG,TEN_TRUONG,TU_NAM,DEN_NAM,ID_XL)
		SELECT ID_UV,TEN_BANG,TEN_TRUONG,TU_NAM,DEN_NAM,ID_XL  FROM #sBTBC A WHERE NOT EXISTS (SELECT * FROM dbo.UNG_VIEN_BANG_CAP B WHERE A.ID_UV = B.ID_UV AND A.ID_BC = B.ID_BC)
		

		--edit Kinh nghiệm làm việc

		DELETE  A FROM dbo.UNG_VIEN_KINH_NGHIEM A WHERE ID_UV = @ID_UV AND NOT EXISTS (SELECT * FROM #sBTKNLV B WHERE A.ID_UV = B.ID_UV AND A.ID_KN = B.ID_KN)
		DBCC CHECKIDENT (UNG_VIEN_KINH_NGHIEM,RESEED,0)
		DBCC CHECKIDENT (UNG_VIEN_KINH_NGHIEM,RESEED)


		UPDATE A
		SET A.TEN_CONG_TY = B.TEN_CONG_TY,A.CHUC_VU = B.CHUC_VU,A.MUC_LUONG =B.MUC_LUONG,A.TU_NAM = B.TU_NAM,A.DEN_NAM = B.DEN_NAM,A.LD_NGHI_VIEC =B.LD_NGHI_VIEC
		FROM dbo.UNG_VIEN_KINH_NGHIEM A
		INNER JOIN #sBTKNLV B ON B.ID_UV = A.ID_UV AND B.ID_KN = A.ID_KN

		INSERT INTO dbo.UNG_VIEN_KINH_NGHIEM(ID_UV,TEN_CONG_TY,CHUC_VU,MUC_LUONG,TU_NAM,DEN_NAM,LD_NGHI_VIEC)
		SELECT ID_UV,TEN_CONG_TY,CHUC_VU,MUC_LUONG,TU_NAM,DEN_NAM,LD_NGHI_VIEC  FROM #sBTKNLV A WHERE NOT EXISTS (SELECT * FROM dbo.UNG_VIEN_KINH_NGHIEM B WHERE A.ID_UV = B.ID_UV AND A.ID_KN = B.ID_KN)
	
	
		--edit thong tin khacs

		DELETE  A FROM dbo.UNG_VIEN_THONG_TIN_KHAC A WHERE ID_UV = @ID_UV AND NOT EXISTS (SELECT * FROM #sBTTTK B WHERE A.ID_UV = B.ID_UV AND A.ID_TTK = B.ID_TTK)
		DBCC CHECKIDENT (UNG_VIEN_THONG_TIN_KHAC,RESEED,0)
		DBCC CHECKIDENT (UNG_VIEN_THONG_TIN_KHAC,RESEED)
		UPDATE A
		SET 
		A.NOI_DUNG = B.NOI_DUNG,A.ID_XL = B.ID_XL
		FROM dbo.UNG_VIEN_THONG_TIN_KHAC A
		INNER JOIN #sBTTTK B ON B.ID_UV = A.ID_UV AND B.ID_TTK = A.ID_TTK

		INSERT INTO dbo.UNG_VIEN_THONG_TIN_KHAC(ID_UV,NOI_DUNG,ID_XL)
		SELECT ID_UV,NOI_DUNG,ID_XL FROM #sBTTTK A WHERE NOT EXISTS (SELECT * FROM dbo.UNG_VIEN_THONG_TIN_KHAC B WHERE A.ID_UV = B.ID_UV AND A.ID_TTK = B.ID_TTK)

		SELECT @ID_UV

    END
GO

