ALTER PROCEDURE [dbo].[spGetListUngVien]
	@UName NVARCHAR = 'admin',
	@NNgu INT = 0,
	@ID_TTTD INT = -1,
	@ID_YCTD INT =-1,
	@ID_KHPV INT =-1,
	@ID_LCV INT = -1
AS
BEGIN
	SELECT A.ID_UV ,MS_UV, HO + ' ' + TEN HO_TEN, CASE PHAI WHEN 0 THEN N'Nữ' ELSE 'Nam' END GIOI_TINH,  DT_DI_DONG,
	(SELECT TEN_LCV FROM dbo.LOAI_CONG_VIEC WHERE ID_LCV =VI_TRI_TD_1 ) AS  VI_TRI_TD_1,
	(SELECT TEN_LCV FROM dbo.LOAI_CONG_VIEC WHERE ID_LCV =VI_TRI_TD_2 ) AS  VI_TRI_TD_2,NGAY_HEN_DI_LAM, ISNULL(XAC_NHAN_DL,0) XAC_NHAN_DL, NGAY_CO_THE_DI_LAM,A.XAC_NHAN_DL, NGAY_NHAN_VIEC, ISNULL(A.DA_GIOI_THIEU,0) DA_GIOI_THIEU, ISNULL(DA_CHUYEN,0) DA_CHUYEN, ISNULL(HUY_TUYEN_DUNG,0) HUY_TUYEN_DUNG
	FROM dbo.UNG_VIEN A
	LEFT JOIN dbo.TT_HON_NHAN B ON A.ID_TT_HN = B.ID_TT_HN
	LEFT JOIN dbo.UNG_VIEN_TUYEN_DUNG C ON A.ID_UV = C.ID_UV
	WHERE (A.DA_TUYEN_DUNG = @ID_TTTD OR @ID_TTTD = -1) AND (C.ID_KHPV = @ID_KHPV OR @ID_KHPV = -1) AND (C.ID_YCTD = @ID_YCTD OR @ID_YCTD = -1)  AND (C.ID_VTTD = @ID_LCV OR @ID_LCV = -1)
	ORDER BY MS_UV
END

--SELECT * FROM UNG_VIEN_PHONG_VAN
--SELECT * FROM PHONG_VAN
--SELECT * FROM UNG_VIEN_TUYEN_DUNG
--SELECT * FROM KE_HOACH_PHONG_VAN
--SELECT * FROM KHPV_VTTD


--SELECT *
--FROM KE_HOACH_PHONG_VAN
GO

