IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'spGetListKHPV')
   exec('CREATE PROCEDURE spGetListKHPV AS BEGIN SET NOCOUNT ON; END')
GO
ALTER PROCEDURE spGetListKHPV
	@TNgay DATETIME,
	@DNgay DATETIME,	
	@UName NVARCHAR(100) ='Admin',  
	@NNgu INT =0 
AS	
BEGIN
SELECT ID_KHPV,SO_KHPV,TIEU_DE,NGAY_LAP,TINH_TRANG,GHI_CHU,PV_ON_OF_LINE,NGUOI_PV_1,NGUOI_PV_2,NGAY_PV FROM dbo.KE_HOACH_PHONG_VAN WHERE NGAY_LAP BETWEEN @TNgay AND @DNgay
END
GO
