
ALTER PROCEDURE [dbo].[spGetListThongTinKhac]  
	@ID_UV BIGINT,
	@UName NVARCHAR(100) ='Admin',  
	@NNgu INT =0 
AS 
BEGIN
	SELECT ID_TTK, ID_UV, NOI_DUNG, T1.ID_XL
	FROM UNG_VIEN_THONG_TIN_KHAC T1 WHERE T1.ID_UV = @ID_UV
END
GO

