IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'spGetComboXepLoai')
   exec('CREATE PROCEDURE spGetComboXepLoai AS BEGIN SET NOCOUNT ON; END')
GO
ALTER PROCEDURE [dbo].[spGetComboXepLoai]
	@Username NVARCHAR(100) ='admin',
	@NNgu INT =0,
	@CoAll BIT=0
AS 
BEGIN
IF @CoAll = 1
BEGIN
SELECT * FROM (
SELECT ID_XL,CASE @NNgu WHEN 0 THEN TEN_XL WHEN 1 THEN ISNULL(NULLIF(TEN_XL_A,''),TEN_XL) ELSE ISNULL(NULLIF(TEN_XL_A,''),TEN_XL) END AS TEN_XL FROM dbo.XEP_LOAI
UNION 
SELECT -1,'< All >')T
ORDER BY T.TEN_XL
END
ELSE
BEGIN
SELECT ID_XL,CASE @NNgu WHEN 0 THEN TEN_XL WHEN 1 THEN ISNULL(NULLIF(TEN_XL_A,''),TEN_XL) ELSE ISNULL(NULLIF(TEN_XL_A,''),TEN_XL) END AS TEN_XL FROM dbo.XEP_LOAI
ORDER BY TEN_XL
END	
END	
GO

