IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[AUTO_CREATE_SO_YCTD]') AND type in (N'FN', N'IF', N'TF', N'FS', N'FT'))
DROP FUNCTION [dbo].[AUTO_CREATE_SO_YCTD]
GO
CREATE FUNCTION [dbo].[AUTO_CREATE_SO_YCTD] (
	@DATE DATETIME )
	RETURNS NVARCHAR(14)
AS 
BEGIN
	DECLARE @STTMAX INT 
	SELECT @STTMAX = MAX(CONVERT(INT,RIGHT (MA_YCTD,2)))  
	FROM dbo.YEU_CAU_TUYEN_DUNG
	WHERE  LEFT(MA_YCTD,2) = 'TP' AND SUBSTRING(MA_YCTD,5,7) = CONVERT(NVARCHAR(7) , GETDATE(), 25)

	DECLARE @STT_NEXT NVARCHAR(10)
	SET @STT_NEXT =  '000' + CONVERT(NVARCHAR(3),ISNULL(@STTMAX,0) +1)

	--SELECT @STT_NEXT 

	DECLARE @ID NVARCHAR(14)
	SET @ID = 'TP-' +  CONVERT(NVARCHAR(7) , GETDATE(), 25)  + '-' +  RIGHT (@STT_NEXT,3)
	RETURN @ID
END
GO

