IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[AUTO_CREATE_SO_UNG_VIEN]') AND type in (N'FN', N'IF', N'TF', N'FS', N'FT'))
DROP FUNCTION [dbo].[AUTO_CREATE_SO_UNG_VIEN]
GO
CREATE FUNCTION [dbo].[AUTO_CREATE_SO_UNG_VIEN] ()
	RETURNS NVARCHAR(14)
AS 
BEGIN
	DECLARE @STTMAX INT 
	SELECT @STTMAX = MAX(CONVERT(INT,RIGHT (MS_UV,6)))  
	FROM dbo.UNG_VIEN

	DECLARE @STT_NEXT NVARCHAR(10)
	SET @STT_NEXT =  '000000' + CONVERT(NVARCHAR(6),ISNULL(@STTMAX,0) +1)
	
	DECLARE @ID NVARCHAR(14)
	SET @ID = 'MUV-' +  +  RIGHT (@STT_NEXT,6)
	RETURN @ID
END
GO


